version: '3.7'
services:
  mylims_filesystem:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      HOST: 0.0.0.0
      NODE_ENV: development
      APP_KEY: E4Z4V7P2bf15oRlGOuUyTUyY7-Sifsiv
    networks:
      - mylims
      - local

networks:
  mylims:
    external:
      name: mylims
  local:
